# Generated by Django 5.2.8 on 2026-08-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_form_builder', '0005_merge_20260820'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlphabetField',
            fields=[
            ],
            options={
                'verbose_name': 'Alphabet field',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djangocms_form_builder.formfield',),
        ),
        migrations.CreateModel(
            name='CountryField',
            fields=[
            ],
            options={
                'verbose_name': 'Country select',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djangocms_form_builder.formfield',),
        ),
    ]
